- prependMsg: "[Pull request auto reviewer](https://github.com/marketplace/actions/pull-request-auto-reviewer)"
- checks:
    - paths: "pnpm-lock.yaml"
      message: |
        - [ ] If you added a new dependency, check our [requirements](https://github.com/hplush/slowreader/blob/main/README.md#dependencies).
    - paths: web/main/
      message: |
        Since you’ve made changes to files in `web/main/` consider these points:

        - Do you need to backport styles changes to `web/public/404.html` or `web/public/500.html`?
        - Think about app loading styles inlined in `index.html`.
    - paths: core/
      message: |
        Since you changed `core/`:
        - [ ] Think about making types more precise. Can you better explain data relations by type?
        - [ ] Think about conflict resolution. We don’t need some very smart changing merging; just 2 changes of the same item on different clients should not break the database. What if the user changes an item on one machine and removes it on another?
        - [ ] Think about log and storage migration.
