version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
      directory: '/.github/actions/deploy'
      schedule:
        interval: weekly
  - package-ecosystem: github-actions
      directory: '/.github/actions/init-node'
      schedule:
        interval: weekly
  - package-ecosystem: pnpm
    directory: '/'
    schedule:
      interval: daily
    security-updates-only: true
  - package-ecosystem: docker
      directory: '/'
      schedule:
        interval: weekly
