packages:
  - api
  - core
  - server
  - web
  - proxy
  - loader-tests
  - extension

forceLegacyDeploy: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici@6.22.0
  - undici-types@6.21.0

blockExoticSubdeps: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - 'postcss-smooth-shadow'
  - '@nanostores/*'
  - '@logux/*'
  - 'logux-eslint-config'
  - '@size-limit/*'
  - 'size-limit'
  - 'browserslist'
  - 'update-browserslist-db'
  - 'caniuse-lite'
  - 'baseline-browser-mapping'
  - 'autoprefixer'
  - 'multiocular'
  - 'oxfmt'
  - '@oxfmt/*'

allowBuilds:
  husky: true
  esbuild: true
