packages:
  - api
  - core
  - server
  - web
  - proxy
  - loader-tests
  - extension

forceLegacyDeploy: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@logux/client'
  - 'postcss-smooth-shadow'

onlyBuiltDependencies:
  - husky
