packages:
  - api
  - core
  - server
  - web
  - proxy
  - loader-tests
  - extension

forceLegacyDeploy: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@nanostores/media-query'
  - '@nanostores/persistent'
  - 'postcss-smooth-shadow'

onlyBuiltDependencies:
  - husky
