packages:
  - api
  - core
  - server
  - web
  - proxy
  - loader-tests
  - extension

forceLegacyDeploy: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080

blockExoticSubdeps: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - 'postcss-smooth-shadow'
  - '@nanostores/*'
  - '@logux/*'
  - 'logux-eslint-config'
  - '@size-limit/*'
  - 'size-limit'
  - 'browserslist'
  - 'update-browserslist-db'
  - 'caniuse-lite'
  - 'baseline-browser-mapping'
  - 'autoprefixer'
  - 'multiocular'
  - 'oxfmt'
  - '@oxfmt/*'

allowBuilds:
  husky: true
  esbuild: true
