packages:
  - api
  - core
  - server
  - web
  - proxy
  - loader-tests
  - extension

forceLegacyDeploy: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - 'postcss-smooth-shadow'
  - '@nanostores/*'
  - '@logux/*'
  - 'browserslist'
  - 'caniuse-lite'

onlyBuiltDependencies:
  - husky
