packages:
  - api
  - core
  - server
  - web
  - proxy
  - loader-tests
  - extension

allowBuilds:
  argon2: false
  esbuild: true
  husky: true
  unrs-resolver: false

blockExoticSubdeps: true

forceLegacyDeploy: true

minimumReleaseAge: 1440

dedupePeers: true

minimumReleaseAgeExclude:
  - postcss
  - postcss-smooth-shadow
  - '@nanostores/*'
  - '@logux/*'
  - '@size-limit/*'
  - size-limit
  - browserslist
  - update-browserslist-db
  - caniuse-lite
  - baseline-browser-mapping
  - autoprefixer
  - multiocular
  - '@logux/oxc-configs'
  - keyux

overrides:
  kysely@>=0.26.0 <0.28.11: '>=0.28.12'
  rollup@<2.80.0: '>=2.80.0'

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080
