packages:
  - api
  - core
  - server
  - web
  - proxy
  - loader-tests
  - extension

forceLegacyDeploy: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici@6.22.0
  - undici-types@6.21.0

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - 'postcss-smooth-shadow'
  - '@nanostores/*'
  - '@logux/*'
  - 'browserslist'
  - 'caniuse-lite'
  - 'autoprefixer'

onlyBuiltDependencies:
  - husky
