packages:
  - api
  - core
  - server
  - web
  - proxy
  - loader-tests
  - extension

allowBuilds:
  esbuild: true
  husky: true
  argon2: false
  unrs-resolver: false

blockExoticSubdeps: true

forceLegacyDeploy: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - postcss-smooth-shadow
  - '@nanostores/*'
  - '@logux/*'
  - logux-eslint-config
  - '@size-limit/*'
  - size-limit
  - browserslist
  - update-browserslist-db
  - caniuse-lite
  - baseline-browser-mapping
  - autoprefixer
  - multiocular

overrides:
  rollup@<2.80.0: '>=2.80.0'

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080
