name: Deploy to Google Cloud
description: We are using it in preview-deploy, server, proxy, main workflows
inputs:
  projectId:
    required: true
    description: Google Cloud project ID
  region:
    required: true
    description: Server location
  folder:
    required: true
    description: What project from monorepo deploy
  registry:
    required: true
    description: Google Cloud Artifacts registry name
  service:
    required: true
    description: Google Cloud Run service name
  tag:
    required: false
    default: latest
    description: Docker image tag
  env:
    required: false
    description: Google Cloud Run environment
  flags:
    required: false
    description: Extra flags for Google Cloud Run deploy command
  shutdown:
    required: false
    description: Shutdown HTTP endpoint
outputs:
  url:
    value: ${{ steps.deploy.outputs.url }}
    description: Deployed app URL
runs:
  using: composite
  steps:
    - name: Build Docker image
      shell: bash
      run: docker build -t ${{ inputs.region }}-docker.pkg.dev/${{ inputs.projectId }}/${{ inputs.registry }}:${{ inputs.tag }} ${{ inputs.folder }}
    - name: Auth Google Cloud
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        workload_identity_provider: projects/300174498438/locations/global/workloadIdentityPools/github/providers/hplush
        service_account: github-deploy@${{ inputs.projectId }}.iam.gserviceaccount.com
    - name: Install Google Cloud
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
    - name: Auth Docker
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev --quiet
    - name: Push Docker image
      shell: bash
      run: docker push ${{ inputs.region }}-docker.pkg.dev/${{ inputs.projectId }}/${{ inputs.registry }}:${{ inputs.tag }}
    - name: Shutdown previous version
      shell: bash
      if: ${{ inputs.shutdown }}
      run: curl -X POST ${{ inputs.shutdown }}
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@2028e2d7d30a78c6910e0632e48dd561b064884d # v3.0.1
      with:
        gcloud_component: beta
        service: ${{ inputs.service }}
        region: ${{ inputs.region }}
        image: ${{ inputs.region }}-docker.pkg.dev/${{ inputs.projectId }}/${{ inputs.registry }}:${{ inputs.tag }}
        tag: ${{ inputs.tag != 'latest' && inputs.tag || '' }}
        no_traffic: ${{ inputs.tag != 'latest' }}
        flags: |
          --allow-unauthenticated
          --set-env-vars="${{ inputs.env }}"
          --service-account=github-deploy@${{ inputs.projectId }}.iam.gserviceaccount.com
          ${{ inputs.flags }}
    - name: Move traffic to new revision
      if: ${{ inputs.tag == 'latest' }}
      shell: bash
      run: |
        gcloud run services update-traffic ${{ inputs.service }} \
          --project ${{ inputs.projectId }} \
          --region ${{ inputs.region }} \
          --to-latest
    - name: Delete previous images
      shell: bash
      run: |
        untagged=$(gcloud artifacts docker images list ${{ inputs.region }}-docker.pkg.dev/${{ inputs.projectId }}/${{ inputs.registry }} --include-tags --format="get(version)" --filter="NOT tags:*")
        for digest in $untagged; do
          image=${{ inputs.region }}-docker.pkg.dev/${{ inputs.projectId }}/${{ inputs.registry }}@$digest
          echo "Deleting unused image: $image"
          gcloud artifacts docker images delete $image --quiet
        done
