name: Deploy to staging
description: Build and push Docker image, then ask the cloud server to deploy it
inputs:
  image-name:
    required: true
    description: Docker image name (e.g. slowreader-web)
  context:
    required: true
    description: Docker build context directory (e.g. ./web/)
  tag:
    required: false
    default: dev
    description: Docker image tag
  domain:
    required: true
    description: Domain of the app on the cloud server (e.g. dev.slowreader.app)
  token:
    required: true
    description: GitHub token for GHCR login
runs:
  using: composite
  steps:
    - name: Build Docker image
      shell: bash
      run: docker build -t ghcr.io/hplush/${INPUTS_IMAGE_NAME}:${INPUTS_TAG} ${INPUTS_CONTEXT}
      env:
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        INPUTS_TAG: ${{ inputs.tag }}
        INPUTS_CONTEXT: ${{ inputs.context }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - name: Push Docker image
      shell: bash
      run: docker push ghcr.io/hplush/${INPUTS_IMAGE_NAME}:${INPUTS_TAG}
      env:
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        INPUTS_TAG: ${{ inputs.tag }}
    - name: Deploy image
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      env:
        DOMAIN: ${{ inputs.domain }}
      with:
        script: |
          let token = await core.getIDToken('https://api.cloud.hplush.dev')
          let response = await fetch(
            `https://api.cloud.hplush.dev/deploy/${process.env.DOMAIN}`,
            { method: 'POST', headers: { authorization: `Bearer ${token}` } }
          )
          let answer = await response.text()
          if (response.ok) core.info(answer)
          else core.setFailed(`${response.status} ${response.statusText}: ${answer}`)
