name: Deploy to staging
description: Build and push Docker image, then trigger Dokploy deployment
inputs:
  image-name:
    required: true
    description: Docker image name (e.g. slowreader-web)
  context:
    required: true
    description: Docker build context directory (e.g. ./web/)
  tag:
    required: false
    default: dev
    description: Docker image tag
  application-id:
    required: true
    description: Dokploy application ID
  cloud:
    required: false
    default: cloud.hplush.dev
    description: Dokploy host
  token:
    required: true
    description: GitHub token for GHCR login
  dokploy-token:
    required: true
    description: Dokploy API token
runs:
  using: composite
  steps:
    - name: Build Docker image
      shell: bash
      run: docker build -t ghcr.io/hplush/${INPUTS_IMAGE_NAME}:${INPUTS_TAG} ${INPUTS_CONTEXT}
      env:
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        INPUTS_TAG: ${{ inputs.tag }}
        INPUTS_CONTEXT: ${{ inputs.context }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - name: Push Docker image
      shell: bash
      run: docker push ghcr.io/hplush/${INPUTS_IMAGE_NAME}:${INPUTS_TAG}
      env:
        INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
        INPUTS_TAG: ${{ inputs.tag }}
    - name: Trigger Dokploy deployment
      shell: bash
      run: |
        curl -X 'POST' \
        'https://${INPUTS_CLOUD}/api/application.deploy' \
        -H 'accept: application/json' \
        -H 'x-api-key: ${INPUTS_DOKPLOY_TOKEN}' \
        -H 'Content-Type: application/json' \
        -d '{
          "applicationId": "${INPUTS_APPLICATION_ID}"
        }'
      env:
        INPUTS_CLOUD: ${{ inputs.cloud }}
        INPUTS_DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        INPUTS_APPLICATION_ID: ${{ inputs.application-id }}
