#!/bin/sh

find "$1" -type f -name "$2" | xargs -I {} -P $(nproc) bash -c '{
  output=$(echo "> {}"; NODE_NO_WARNINGS=1 pnpm tsm {})

  if [[ $? -ne 0 ]]; then
    echo "$output"
    exit 1
  fi
  echo "$output"
}'

