name: Core Tests
on:
  push:
    branches:
      - main
    paths:
      - pnpm-lock.yaml
      - .tool-versions
      - core/**
  pull_request:
    paths:
      - pnpm-lock.yaml
      - .tool-versions
      - core/**
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Run tests
        run: pnpm test-core
