name: Core Tests
on:
  push:
    branches:
      - main
    paths:
      - 'pnpm-lock.yaml'
      - '.tool-versions'
      - '.github/workflows/core.yml'
      - 'core/**'
  pull_request:
    paths:
      - 'pnpm-lock.yaml'
      - '.tool-versions'
      - '.github/workflows/core.yml'
      - 'core/**'
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Run tests
        run: cd core && pnpm test
        env:
          FORCE_COLOR: 1
