name: Deploy Staging
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main
      - deploy
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1
      - name: Install dependencies
        run: pnpm install --ignore-scripts --prod
      - name: Build static files
        run: cd web && pnpm build
      - name: Auth Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: slowreader
          workload_identity_provider: projects/265562628911/locations/global/workloadIdentityPools/github/providers/slowreader
          service_account: github-deploy@slowreader.iam.gserviceaccount.com
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: dev
          region: europe-west6
          source: ./web/
