name: Daily Check Feeds
on:
  schedule:
    - cron: '00 23 * * *' # Runs at midnight UTC every day
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Check feeds
        run: pnpm check-feeds
