name: Close Preview
on:
  pull_request:
    types:
      - closed
    paths-ignore:
      - '**/*.md'
      - 'scripts/**'
      - '.vscode/**'
      - '.githooks/**'
      - '.github/**'
      - 'core/test/**'
      - 'proxy/test/**'
      - 'server/test/**'
      - 'loader-tests/**'
      - '.devcontainer/**'
      - 'extension/**'
permissions:
  contents: read
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy-preview')
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: Save PR number
        run: echo "${{ github.event.pull_request.number }}" > ./preview-id
      - name: Save data for another workflow
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: preview-id
          retention-days: 1
          path: |
            ./preview-id
