name: Server
on:
  push:
    branches:
      - main
    paths:
      - 'server/*'
      - 'server/**/*'
      - '!server/*.md'
      - 'pnpm-lock.yaml'
      - '.github/workflows/server.yml'
      - '.github/actions/init-node/action.yml'
  pull_request:
    paths:
      - 'server/*'
      - 'server/**/*'
      - '!server/*.md'
      - 'pnpm-lock.yaml'
      - '.github/workflows/server.yml'
      - '.github/actions/init-node/action.yml'
jobs:
  test:
    name: Server Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            nodejs.org:443
            release-assets.githubusercontent.com
            objects.githubusercontent.com:443
            registry.npmjs.org:443
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Initialize Node.js
        uses: ./.github/actions/init-node
      - name: Run tests
        run: cd server && pnpm test
  build:
    name: Server Build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            nodejs.org:443
            release-assets.githubusercontent.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
            storybook.js.org:443
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Initialize Node.js
        uses: ./.github/actions/init-node
        with:
          cache: false
          install: -F server -F proxy -F api -F web -F core --prod
      - name: Build web client
        run: cd web && node --run build
      - name: Build server
        run: cd server && node --run build
      - name: Create archive to keep symlinks
        run: tar -cf server.tar server/dist/ server/web/
      - name: Upload server build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: server-build-${{ github.sha }}
          retention-days: 1
          path: |
            ./server.tar
  staging:
    name: Server Staging Deploy
    needs:
      - test
      - build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    concurrency:
      group: staging-server
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          allowed-endpoints: >
            9236a389bd48b984df91adc1bc924620.r2.cloudflarestorage.com:443
            api.github.com:443
            apk.cgr.dev:443
            cgr.dev:443
            github.com:443
            nodejs.org:443
            release-assets.githubusercontent.com:443
            raw.githubusercontent.com:443
            ghcr.io:443
            pkg-containers.githubusercontent.com:443
            cloud.hplush.dev:443
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download server build from previous step
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: server-build-${{ github.sha }}
          path: ./
      - name: Extract archive to restore symlinks
        run: tar -xf server.tar
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          image-name: slowreader
          context: ./server/
          application-id: 3b5AqgMLia13ku53keAJC
          token: ${{ secrets.GITHUB_TOKEN }}
          dokploy-token: ${{ secrets.DOKPLOY_TOKEN }}
